import 'package:rentora/feature/models/home_model.dart';

final List<HomeModel> allHomes = [
  HomeModel(
    id: '103921',
    type: 'Sotuv',
    title: '2 xonali kvartira',
    price: '40 000 y.e.',
    address: 'Savunana-9A, Vashnahad tumani',
    rooms: '2 xonali',
    floor: '2/2 qavat',
    time: '28/05/2025 16:37',
    views: '23 daqiqa oldin',
    image: 'assets/images/image1.jpg',
    description:
        'Uyi kiriditi bor\nUch tomonlama shartnoma bilan\nBehovotir nomilaga otqizib beraman',
    area: 42.0,
    renovation: 'Kosmetik',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 30.0,
    balcony: '1',
    security: 'Kuzatuv kameralari, Kodlangan eshik',
  ),
  HomeModel(
    id: '103922',
    type: 'Sotuv',
    title: 'Zamonaviy 3 xonali kvartira',
    price: '12000 y.e.',
    address: 'Toshkent, Yakkasaroy tumani',
    rooms: '3 xonali',
    floor: '2/5 qavat',
    time: '1 soat oldin',
    views: '145 ta ko‘rildi',
    image: 'assets/images/image2.jpg',
    description:
        'Yangi qurilgan binoda, mebel bilan, barcha qulayliklar mavjud',
    area: 65.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 55.0,
    balcony: '2',
    security: "Kuzatuv kameralari, Qo'riqchi",
  ),
  HomeModel(
    id: '103923',
    type: 'Sotuv',
    title: 'Yangi ta\'mirdan chiqqan 2 xonali',
    price: '10500 y.e.',
    address: 'Toshkent, Chilonzor tumani',
    rooms: '2 xonali',
    floor: '4/6 qavat',
    time: '3 soat oldin',
    views: '210 ta ko‘rildi',
    image: 'assets/images/image3.jpg',
    description: 'Yaqinda ta\'mirlangan, barcha jihozlar yangi, metroga yaqin',
    area: 48.0,
    renovation: 'Yangi',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 38.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103924',
    type: 'Ofis',
    title: 'Ko‘p qavatli uyda 1 xonali',
    price: '9000 y.e.',
    address: 'Toshkent, Olmazor tumani',
    rooms: '1 xonali',
    floor: '1/4 qavat',
    time: '5 soat oldin',
    views: '98 ta ko‘rildi',
    image: 'assets/images/image4.jpg',
    description: 'Talabalar uchun qulay, oshxona jihozlari bor',
    area: 35.0,
    renovation: 'O\'rtacha',
    buildingType: "Panel",
    bathroomType: 'Umumiy',
    livingArea: 28.0,
    balcony: '0',
    security: '-',
  ),
  HomeModel(
    id: '103925',
    type: 'Sotuv',
    title: 'Metroga yaqin 4 xonali kvartira',
    price: '13500 y.e.',
    address: 'Toshkent, Yunusobod tumani',
    rooms: '4 xonali',
    floor: '5/9 qavat',
    time: '7 soat oldin',
    views: '188 ta ko‘rildi',
    image: 'assets/images/image5.jpg',
    description: 'Katta oilalar uchun ideal, bolalar maydoni yaqinida',
    area: 85.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 72.0,
    balcony: '2',
    security: "Kuzatuv kameralari, Qo'riqchi",
  ),
  HomeModel(
    id: '103926',
    type: 'Ofis',
    title: 'Arzon 2 xonali uy',
    price: '8500 y.e.',
    address: 'Toshkent, Uchtepa tumani',
    rooms: '2 xonali',
    floor: '3/5 qavat',
    time: '10 soat oldin',
    views: '130 ta ko‘rildi',
    image: 'assets/images/image6.jpg',
    description: 'Ijara uchun qulay, tejamkor variant',
    area: 45.0,
    renovation: 'Oddiy',
    buildingType: "Panel",
    bathroomType: 'Alohida',
    livingArea: 38.0,
    balcony: '1',
    security: '-',
  ),
  HomeModel(
    id: '103927',
    type: 'Ofis',
    title: 'Muhtasham 3 xonali kvartira',
    price: '12800 y.e.',
    address: 'Toshkent, Yashnobod tumani',
    rooms: '3 xonali',
    floor: '6/8 qavat',
    time: '12 soat oldin',
    views: '210 ta ko‘rildi',
    image: 'assets/images/image7.jpg',
    description: 'Nufuzli hududda, yuqori sifatli ta\'mir',
    area: 75.0,
    renovation: 'Dizayn',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 65.0,
    balcony: '2',
    security: 'Kuzatuv kameralari, Xavfsizlik tizimi',
  ),
  HomeModel(
    id: '103928',
    type: 'Ofis',
    title: 'Shinam 1 xonali uy',
    price: '7800 y.e.',
    address: 'Toshkent, Shayxontohur tumani',
    rooms: '1 xonali',
    floor: '2/5 qavat',
    time: '15 soat oldin',
    views: '85 ta ko‘rildi',
    image: 'assets/images/image8.jpg',
    description: 'Yakka shaxslar uchun qulay, markaziy joylashuv',
    area: 38.0,
    renovation: 'Yangi',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 32.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103929',
    type: 'Ofis',
    title: 'Remontli 4 xonali kvartira',
    price: '14000 y.e.',
    address: 'Toshkent, Chilonzor tumani',
    rooms: '4 xonali',
    floor: '4/6 qavat',
    time: '17 soat oldin',
    views: '232 ta ko‘rildi',
    image: 'assets/images/image9.jpg',
    description: 'Oilaviy turar joy, barcha zamonaviy qulayliklar',
    area: 90.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 78.0,
    balcony: '2',
    security: "Kuzatuv kameralari, Qo'riqchi",
  ),
  HomeModel(
    id: '103930',
    type: 'Ofis',
    title: '2 xonali, barcha sharoitlar bor',
    price: '9700 y.e.',
    address: 'Toshkent, Yakkasaroy tumani',
    rooms: '2 xonali',
    floor: '3/5 qavat',
    time: '20 soat oldin',
    views: '112 ta ko‘rildi',
    image: 'assets/images/image10.jpg',
    description: 'Konditsioner, sovutgich, kir yuvish mashinasi bilan',
    area: 50.0,
    renovation: 'Yangi',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 42.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103931',
    type: 'Sotuv',
    title: 'Yangi qurilgan 3 xonali kvartira',
    price: '15000 y.e.',
    address: 'Toshkent, Mirzo Ulug\'bek tumani',
    rooms: '3 xonali',
    floor: '5/9 qavat',
    time: '1 kun oldin',
    views: '245 ta ko‘rildi',
    image: 'assets/images/image11.jpg',
    description: 'Yangi binoda, dizayn loyiha asosida qurilgan',
    area: 68.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 58.0,
    balcony: '2',
    security: 'Kuzatuv kameralari, Xavfsizlik tizimi',
  ),
  HomeModel(
    id: '103932',
    type: 'Ijaraga',
    title: 'Markazdagi 1 xonali kvartira',
    price: '9500 y.e.',
    address: 'Toshkent, Mirobod tumani',
    rooms: '1 xonali',
    floor: '3/5 qavat',
    time: '2 kun oldin',
    views: '176 ta ko‘rildi',
    image: 'assets/images/image12.jpg',
    description: 'Ish joyiga yaqin, barcha infratuzilma mavjud',
    area: 40.0,
    renovation: 'Yangi',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 32.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103933',
    type: 'Sotuv',
    title: '5 xonali hashamatli kvartira',
    price: '25000 y.e.',
    address: 'Toshkent, Yunusobod tumani',
    rooms: '5 xonali',
    floor: '7/12 qavat',
    time: '3 kun oldin',
    views: '320 ta ko‘rildi',
    image: 'assets/images/image13.jpg',
    description: 'Premium segment, yuqori qavatdagi manzara',
    area: 120.0,
    renovation: 'Dizayn',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 95.0,
    balcony: '3',
    security: 'Kuzatuv kameralari, Xavfsizlik tizimi, Qo\'riqchi',
  ),
  HomeModel(
    id: '103934',
    type: 'Ijaraga',
    title: 'Talabalar uchun 2 xonali',
    price: '8000 y.e.',
    address: 'Toshkent, Sergeli tumani',
    rooms: '2 xonali',
    floor: '1/5 qavat',
    time: '4 kun oldin',
    views: '154 ta ko‘rildi',
    image: 'assets/images/image14.jpg',
    description: 'Universitetga yaqin, arzon narxda',
    area: 42.0,
    renovation: 'O\'rtacha',
    buildingType: "Panel",
    bathroomType: 'Alohida',
    livingArea: 36.0,
    balcony: '1',
    security: '-',
  ),
  HomeModel(
    id: '103935',
    type: 'Sotuv',
    title: 'G\'ishtli binoda 3 xonali',
    price: '13500 y.e.',
    address: 'Toshkent, Shayxontohur tumani',
    rooms: '3 xonali',
    floor: '3/5 qavat',
    time: '5 kun oldin',
    views: '198 ta ko‘rildi',
    image: 'assets/images/image15.jpg',
    description: 'Sokin hudud, bolalar bog\'chasi yaqinida',
    area: 62.0,
    renovation: 'Yevro',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 52.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103936',
    type: 'Ijaraga',
    title: 'Yangi ta\'mirlangan 1 xonali',
    price: '8500 y.e.',
    address: 'Toshkent, Chilonzor tumani',
    rooms: '1 xonali',
    floor: '4/9 qavat',
    time: '6 kun oldin',
    views: '132 ta ko‘rildi',
    image: 'assets/images/image16.jpg',
    description: 'Metroga 5 daqiqa piyoda, yangi mebel',
    area: 38.0,
    renovation: 'Yangi',
    buildingType: "Panel",
    bathroomType: 'Alohida',
    livingArea: 30.0,
    balcony: '1',
    security: '-',
  ),
  HomeModel(
    id: '103937',
    type: 'Sotuv',
    title: '4 xonali oilaviy kvartira',
    price: '18000 y.e.',
    address: 'Toshkent, Yakkasaroy tumani',
    rooms: '4 xonali',
    floor: '2/5 qavat',
    time: '7 kun oldin',
    views: '210 ta ko‘rildi',
    image: 'assets/images/image17.jpg',
    description: 'Katta oilalar uchun ideal, 2 hammom bor',
    area: 82.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 70.0,
    balcony: '2',
    security: "Kuzatuv kameralari, Qo'riqchi",
  ),
  HomeModel(
    id: '103938',
    type: 'Ijaraga',
    title: 'Ishchilar uchun 2 xonali',
    price: '7500 y.e.',
    address: 'Toshkent, Olmazor tumani',
    rooms: '2 xonali',
    floor: '1/4 qavat',
    time: '8 kun oldin',
    views: '98 ta ko‘rildi',
    image: 'assets/images/image18.jpg',
    description: 'Ish joyiga yaqin, oddiy sharoitlar',
    area: 45.0,
    renovation: 'Oddiy',
    buildingType: "Panel",
    bathroomType: 'Alohida',
    livingArea: 38.0,
    balcony: '0',
    security: '-',
  ),
  HomeModel(
    id: '103939',
    type: 'Sotuv',
    title: '3 xonali yangi kvartira',
    price: '16000 y.e.',
    address: 'Toshkent, Yunusobod tumani',
    rooms: '3 xonali',
    floor: '6/12 qavat',
    time: '9 kun oldin',
    views: '225 ta ko‘rildi',
    image: 'assets/images/image19.jpg',
    description: 'Yangi qurilgan binoda, lift bor',
    area: 70.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 60.0,
    balcony: '2',
    security: 'Kuzatuv kameralari, Xavfsizlik tizimi',
  ),
  HomeModel(
    id: '103940',
    type: 'Ijaraga',
    title: '1 xonali arzon kvartira',
    price: '7000 y.e.',
    address: 'Toshkent, Uchtepa tumani',
    rooms: '1 xonali',
    floor: '2/4 qavat',
    time: '10 kun oldin',
    views: '120 ta ko‘rildi',
    image: 'assets/images/image20.jpg',
    description: 'Ijara uchun eng arzon variant',
    area: 32.0,
    renovation: 'Oddiy',
    buildingType: "Panel",
    bathroomType: 'Umumiy',
    livingArea: 25.0,
    balcony: '0',
    security: '-',
  ),
  HomeModel(
    id: '103941',
    type: 'Sotuv',
    title: '2 xonali yangi ta\'mir',
    price: '12500 y.e.',
    address: 'Toshkent, Shayxontohur tumani',
    rooms: '2 xonali',
    floor: '3/5 qavat',
    time: '11 kun oldin',
    views: '178 ta ko‘rildi',
    image: 'assets/images/image21.jpg',
    description: 'Yaqinda ta\'mirlangan, barcha jihozlar yangi',
    area: 50.0,
    renovation: 'Yangi',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 42.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103942',
    type: 'Ijaraga',
    title: '3 xonali oilaviy kvartira',
    price: '11000 y.e.',
    address: 'Toshkent, Mirzo Ulug\'bek tumani',
    rooms: '3 xonali',
    floor: '4/7 qavat',
    time: '12 kun oldin',
    views: '195 ta ko‘rildi',
    image: 'assets/images/image22.jpg',
    description: 'Oilaviy turar joy, bolalar maydoni yaqinida',
    area: 65.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 55.0,
    balcony: '1',
    security: "Kuzatuv kameralari, Qo'riqchi",
  ),
  HomeModel(
    id: '103943',
    type: 'Sotuv',
    title: '4 xonali keng kvartira',
    price: '22000 y.e.',
    address: 'Toshkent, Yashnobod tumani',
    rooms: '4 xonali',
    floor: '3/5 qavat',
    time: '13 kun oldin',
    views: '240 ta ko‘rildi',
    image: 'assets/images/image23.jpg',
    description: 'Keng xonalar, oilaviy turar joy uchun ajoyib',
    area: 95.0,
    renovation: 'Dizayn',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 80.0,
    balcony: '2',
    security: 'Kuzatuv kameralari, Xavfsizlik tizimi',
  ),
  HomeModel(
    id: '103944',
    type: 'Ijaraga',
    title: '1 xonali yangi kvartira',
    price: '8800 y.e.',
    address: 'Toshkent, Chilonzor tumani',
    rooms: '1 xonali',
    floor: '5/9 qavat',
    time: '14 kun oldin',
    views: '145 ta ko‘rildi',
    image: 'assets/images/image24.jpg',
    description: 'Yangi qurilgan binoda, lift bor',
    area: 36.0,
    renovation: 'Yangi',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 30.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103945',
    type: 'Sotuv',
    title: '2 xonali shinam kvartira',
    price: '11500 y.e.',
    address: 'Toshkent, Yakkasaroy tumani',
    rooms: '2 xonali',
    floor: '2/5 qavat',
    time: '15 kun oldin',
    views: '165 ta ko‘rildi',
    image: 'assets/images/image25.jpg',
    description: 'Markaziy hududda, barcha qulayliklar mavjud',
    area: 48.0,
    renovation: 'Yevro',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 40.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103946',
    type: 'Ijaraga',
    title: '3 xonali arzon kvartira',
    price: '9500 y.e.',
    address: 'Toshkent, Sergeli tumani',
    rooms: '3 xonali',
    floor: '1/5 qavat',
    time: '16 kun oldin',
    views: '132 ta ko‘rildi',
    image: 'assets/images/image26.jpg',
    description: 'Katta maydonda arzon narxda',
    area: 60.0,
    renovation: 'O\'rtacha',
    buildingType: "Panel",
    bathroomType: 'Alohida',
    livingArea: 52.0,
    balcony: '1',
    security: '-',
  ),
  HomeModel(
    id: '103947',
    type: 'Sotuv',
    title: '4 xonali yangi qurilgan',
    price: '19500 y.e.',
    address: 'Toshkent, Yunusobod tumani',
    rooms: '4 xonali',
    floor: '7/12 qavat',
    time: '17 kun oldin',
    views: '210 ta ko‘rildi',
    image: 'assets/images/image27.jpg',
    description: 'Yangi binoda, yuqori qavatdagi manzara',
    area: 88.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 75.0,
    balcony: '2',
    security: 'Kuzatuv kameralari, Xavfsizlik tizimi',
  ),
  HomeModel(
    id: '103948',
    type: 'Ijaraga',
    title: '1 xonali oddiy kvartira',
    price: '6500 y.e.',
    address: 'Toshkent, Olmazor tumani',
    rooms: '1 xonali',
    floor: '1/4 qavat',
    time: '18 kun oldin',
    views: '110 ta ko‘rildi',
    image: 'assets/images/image28.jpg',
    description: 'Ijara uchun eng arzon variant',
    area: 30.0,
    renovation: 'Oddiy',
    buildingType: "Panel",
    bathroomType: 'Umumiy',
    livingArea: 25.0,
    balcony: '0',
    security: '-',
  ),
  HomeModel(
    id: '103949',
    type: 'Sotuv',
    title: '3 xonali yangi ta\'mir',
    price: '14500 y.e.',
    address: 'Toshkent, Shayxontohur tumani',
    rooms: '3 xonali',
    floor: '4/5 qavat',
    time: '19 kun oldin',
    views: '185 ta ko‘rildi',
    image: 'assets/images/image29.jpg',
    description: 'Yaqinda ta\'mirlangan, barcha jihozlar yangi',
    area: 68.0,
    renovation: 'Yangi',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 58.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103950',
    type: 'Ijaraga',
    title: '2 xonali oilaviy kvartira',
    price: '10200 y.e.',
    address: 'Toshkent, Mirzo Ulug\'bek tumani',
    rooms: '2 xonali',
    floor: '3/7 qavat',
    time: '20 kun oldin',
    views: '155 ta ko‘rildi',
    image: 'assets/images/image30.jpg',
    description: 'Oilaviy turar joy, bolalar maydoni yaqinida',
    area: 52.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 45.0,
    balcony: '1',
    security: "Kuzatuv kameralari, Qo'riqchi",
  ),
  HomeModel(
    id: '103951',
    type: 'Sotuv',
    title: '4 xonali keng kvartira',
    price: '21000 y.e.',
    address: 'Toshkent, Yashnobod tumani',
    rooms: '4 xonali',
    floor: '4/5 qavat',
    time: '21 kun oldin',
    views: '230 ta ko‘rildi',
    image: 'assets/images/image31.jpg',
    description: 'Keng xonalar, oilaviy turar joy uchun ajoyib',
    area: 92.0,
    renovation: 'Dizayn',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 78.0,
    balcony: '2',
    security: 'Kuzatuv kameralari, Xavfsizlik tizimi',
  ),
  HomeModel(
    id: '103952',
    type: 'Ijaraga',
    title: '1 xonali yangi kvartira',
    price: '9200 y.e.',
    address: 'Toshkent, Chilonzor tumani',
    rooms: '1 xonali',
    floor: '6/9 qavat',
    time: '22 kun oldin',
    views: '140 ta ko‘rildi',
    image: 'assets/images/image32.jpg',
    description: 'Yangi qurilgan binoda, lift bor',
    area: 38.0,
    renovation: 'Yangi',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 32.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103953',
    type: 'Sotuv',
    title: '2 xonali shinam kvartira',
    price: '12500 y.e.',
    address: 'Toshkent, Yakkasaroy tumani',
    rooms: '2 xonali',
    floor: '3/5 qavat',
    time: '23 kun oldin',
    views: '175 ta ko‘rildi',
    image: 'assets/images/image33.jpg',
    description: 'Markaziy hududda, barcha qulayliklar mavjud',
    area: 50.0,
    renovation: 'Yevro',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 42.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103954',
    type: 'Ijaraga',
    title: '3 xonali arzon kvartira',
    price: '9800 y.e.',
    address: 'Toshkent, Sergeli tumani',
    rooms: '3 xonali',
    floor: '2/5 qavat',
    time: '24 kun oldin',
    views: '142 ta ko‘rildi',
    image: 'assets/images/image34.jpg',
    description: 'Katta maydonda arzon narxda',
    area: 62.0,
    renovation: 'O\'rtacha',
    buildingType: "Panel",
    bathroomType: 'Alohida',
    livingArea: 54.0,
    balcony: '1',
    security: '-',
  ),
  HomeModel(
    id: '103955',
    type: 'Sotuv',
    title: '4 xonali yangi qurilgan',
    price: '20500 y.e.',
    address: 'Toshkent, Yunusobod tumani',
    rooms: '4 xonali',
    floor: '8/12 qavat',
    time: '25 kun oldin',
    views: '220 ta ko‘rildi',
    image: 'assets/images/image35.jpg',
    description: 'Yangi binoda, yuqori qavatdagi manzara',
    area: 90.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 77.0,
    balcony: '2',
    security: 'Kuzatuv kameralari, Xavfsizlik tizimi',
  ),
  HomeModel(
    id: '103956',
    type: 'Ijaraga',
    title: '1 xonali oddiy kvartira',
    price: '6800 y.e.',
    address: 'Toshkent, Olmazor tumani',
    rooms: '1 xonali',
    floor: '2/4 qavat',
    time: '26 kun oldin',
    views: '115 ta ko‘rildi',
    image: 'assets/images/image36.jpg',
    description: 'Ijara uchun eng arzon variant',
    area: 32.0,
    renovation: 'Oddiy',
    buildingType: "Panel",
    bathroomType: 'Umumiy',
    livingArea: 26.0,
    balcony: '0',
    security: '-',
  ),
  HomeModel(
    id: '103957',
    type: 'Sotuv',
    title: '3 xonali yangi ta\'mir',
    price: '15500 y.e.',
    address: 'Toshkent, Shayxontohur tumani',
    rooms: '3 xonali',
    floor: '5/5 qavat',
    time: '27 kun oldin',
    views: '195 ta ko‘rildi',
    image: 'assets/images/image37.jpg',
    description: 'Yaqinda ta\'mirlangan, barcha jihozlar yangi',
    area: 72.0,
    renovation: 'Yangi',
    buildingType: "G'isht",
    bathroomType: 'Alohida',
    livingArea: 62.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
  HomeModel(
    id: '103958',
    type: 'Ijaraga',
    title: '2 xonali oilaviy kvartira',
    price: '10800 y.e.',
    address: 'Toshkent, Mirzo Ulug\'bek tumani',
    rooms: '2 xonali',
    floor: '4/7 qavat',
    time: '28 kun oldin',
    views: '165 ta ko‘rildi',
    image: 'assets/images/image38.jpg',
    description: 'Oilaviy turar joy, bolalar maydoni yaqinida',
    area: 55.0,
    renovation: 'Yevro',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 47.0,
    balcony: '1',
    security: "Kuzatuv kameralari, Qo'riqchi",
  ),
  HomeModel(
    id: '103959',
    type: 'Sotuv',
    title: '4 xonali keng kvartira',
    price: '23000 y.e.',
    address: 'Toshkent, Yashnobod tumani',
    rooms: '4 xonali',
    floor: '5/5 qavat',
    time: '29 kun oldin',
    views: '245 ta ko‘rildi',
    image: 'assets/images/image39.jpg',
    description: 'Keng xonalar, oilaviy turar joy uchun ajoyib',
    area: 98.0,
    renovation: 'Dizayn',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 82.0,
    balcony: '2',
    security: 'Kuzatuv kameralari, Xavfsizlik tizimi',
  ),
  HomeModel(
    id: '103960',
    type: 'Ijaraga',
    title: '1 xonali yangi kvartira',
    price: '9400 y.e.',
    address: 'Toshkent, Chilonzor tumani',
    rooms: '1 xonali',
    floor: '7/9 qavat',
    time: '30 kun oldin',
    views: '150 ta ko‘rildi',
    image: 'assets/images/image40.jpg',
    description: 'Yangi qurilgan binoda, lift bor',
    area: 40.0,
    renovation: 'Yangi',
    buildingType: "Monolit",
    bathroomType: 'Alohida',
    livingArea: 34.0,
    balcony: '1',
    security: 'Kodli eshik',
  ),
];
